### ISSUE TITLE
REGRESSION: user can get corrupted data

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-rgw#222]
https://github.com/Seagate/cortx-rgw/blob/d70996c7605feb473b25465e81d18c2d825dea43/src/rgw/rgw_sal_motr.cc#L2143

This is wrong. This may end up with corrupted data.

For example, if some unit was not written due to the server failure, we will get zeros for this unit on read without any error, so the user even will not know he is getting corrupted object data.

See more at https://github.com/Seagate/cortx-motr/pull/1728.

_Originally posted by @andriytk in https://github.com/Seagate/cortx-rgw/pull/217#discussion_r880944394_

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31594. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Amit Kapil commented in Jira Server:

Deepak, This is part of the PR 223. Lets address this quickly and get the build out. Thanks

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. cortx-rgw - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Andriy Tkachuk
* Component Build  :  5126 
* Release Build    :  5492  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5492 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5492
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5492
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5492
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5492 
{panel}

**Comment by cortx-admin** [comment]
> Amit Kapil commented in Jira Server:

This is addressed with PR223 PR from RGW. This is merged and available in main in 791 build

**Comment by cortx-admin** [comment]
> Deepak Mahale commented in Jira Server:

PR Raised approved and merged.

**Comment by cortx-admin** [comment]
> Deepak Mahale commented in Jira Server:

PR Merged to Main

**Comment by cortx-admin** [comment]
> Kapil Jinna commented in Jira Server:

Verified this ticket as part of testing done in https://jts.seagate.com/browse/CORTX-31575

Hence closing this ticket.
