### ISSUE TITLE
Codacy: code style issue with ADDB code changes

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx-rgw#315]
# [Codacy]([https://app.codacy.com/gh/Seagate/cortx-rgw/commit?cid=645730441]) detected an issue:
 ## Message: `[fenced-code-flag] Missing code language flag`

 # Currently on:
 + **Commit**: 98d8ef1c8509e2f31cb37166a32460ead54007d5
 + **File**: [src/rgw/motr/addb/README.md]([https://github.com/Seagate/cortx-rgw/blob/98d8ef1c8509e2f31cb37166a32460ead54007d5/src/rgw/motr/addb/README.md])
 + **LineNum**: [5]([https://github.com/Seagate/cortx-rgw/blob/98d8ef1c8509e2f31cb37166a32460ead54007d5/src/rgw/motr/addb/README.md#L5])

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32335. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Amit Kapil commented in Jira Server:

[~520479] Please help get this resolved. Must not take more than 5 mins of time.

**Comment by cortx-admin** [comment]
> Maxim Malezhin commented in Jira Server:

Ready for review, PR has been created
[rgw_sal_motr: Fix Codacy warning in ADDB readme file by maximalezhin · Pull Request #357 · Seagate/cortx-rgw (github.com)|https://github.com/Seagate/cortx-rgw/pull/357]

**Comment by cortx-admin** [comment]
> Maxim Malezhin commented in Jira Server:

PR has been reviewed and merged

**Comment by cortx-admin** [comment]
> Maxim Malezhin commented in Jira Server:

Completed
