### ISSUE TITLE
Multi-part uploads fail when some server is offline

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-rgw#422]
Currently, we create an additional index for each multipart uploaded object to store its parts. If some server is down, the index creation operation would fail, thus failing the multipart upload.

So we should avoid creating indexes on multipart uploads. It's not only a heavyweight operation in motr, but also not fault-tolerant atm ([to be fixed in motr](https://github.com/Seagate/cortx-motr/issues/2142) later). For example, when we create a bucket, in addition to the bucket-index we can create a bucket-mp-index to store the objects' parts.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34181. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Amit Kapil commented in Jira Server:

This is the new design we need to evaluate [~689935] [~520414] and [~722075]

**Comment by cortx-admin** [comment]
> Andriy Tkachuk commented in Jira Server:

Ready for review at https://github.com/Seagate/cortx-rgw/pull/429/.

**Comment by cortx-admin** [comment]
> Andriy Tkachuk commented in Jira Server:

Landed.

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. cortx-rgw - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: noreply
* Component Build  :  5260 
* Release Build    :  6062  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/6062 

h3. Image Location  :  
*  null
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-6062
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6062
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6062 
{panel}
