### ISSUE TITLE
Clean up partially written objects with GC

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-rgw#7]
Currently, if an object write fails somewhere in the middle of operation (due to RGW crash, for example) - the written data is not cleaned up. We should involve RGW's built-in GC mechanism to clean up the partially written data and avoid the storage leakage.

The possible design can be like this: before writing or updating any object, we should generate the new motr-fid for it (see https://github.com/Seagate/cortx-rgw/issues/5) and add it's S3-name (user+bucket+key) and the generated fid into the global gc-queue index in motr. S3-name and the fid should be the key entry in this gc-queue-index, and the value should be the date+time of when the entry was created.

RGW's GC-processes (on each RGW instance) periodically will check this global gc-queue-index in Motr and, if the object is not present in the bucket index - delete it's possibly incomplete data from Motr and its record from the queue. That's the basic idea of the algorithm.

Now, it's possible that the object is still being written and that's the reason why it's not available in the bucket index yet. To solve this problem, GC-process should check the timestamp of the record: if it was created more than, say, an hour ago, and it's still not present in the bucket index - it's definitely a stale object, and it should be removed.

When the s3-object is updated (overwritten), before writing its new metadata record into the bucket index, we should add its old fid into the gc-queue for the cleanup. Also, when we delete an object, we should write its name and fid into the gc-queue before deleting its record from the bucket index, so that the actual data is deleted by GC later - this will improve the performance of deletions also. (For deletions, we can put zero as the timestamp-value, so that the object could be deleted immediately by GC.)

Here is the sequence diagram of how an s3-object overwrite case might look like:

```mermaid
sequenceDiagram
Client->>rgw: Write s3-object
rgw->>rgw: generate unique motr fid
rgw->>Motr: Put generated fid to GC queue
rgw->>Motr: Write object data
Motr-->>rgw: Success
rgw->>Motr: Get old s3-object metadata (motr fid, etc.)
Motr-->>rgw: Result
alt the old object is present
rgw->>Motr: Put old object fid to GC queue
end
rgw->>Motr: Put new s3-object metadata
Motr-->>rgw: Success
rgw-->>Client: Success
Note right of rgw: After some time... GC wakes up
rgw->>Motr: Fetch next objects batch from the GC queue
Motr-->>rgw: Result
loop by each object from the result
rgw->>Motr: Check object in the bucket index
Motr-->>rgw: Result
alt Object is absent in the bucket index for more than 1hr?
rgw->>Motr: Delete stale object data
Motr-->>rgw: Success
rgw->>Motr: Delete object from GC queue
end
alt Object is present in the bucket index?
rgw->>Motr: Delete object from GC queue
end
end
```

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-28849. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by johnbent** [comment]
If there are a billion objects in the system, how long will the GC scan take? Is this a concern? Why not instead use a WAL log that has a checkpoint location and a marker for intent to create and a marker for successful completion. Then the scan just works forward from the WAL checkpoint and moves the checkpoint forward and truncates old WAL items. We have a bounded scan time.

**Comment by andriytk** [comment]
GC queue does contain only those objects which are currently being written or were written recently, before the last GC-thread processed the queue. So you can regard it as such distributed WAL-log, essentially.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
